#!/usr/bin/env php
<?php

!defined('APP_BASE_PATH') && define('APP_BASE_PATH', __DIR__ . '/');

if (extension_loaded('jsonnet')) {
    !defined('CONFIG_FORMAT') && define('CONFIG_FORMAT', 'array,jsonnet');
}

!defined('RAW_FUNCTIONS') && define('RAW_FUNCTIONS', false);

require_once __DIR__ . '/vendor/autoload.php';

(new \SwFwLess\bootstrap\Command())->run();
