<?php

return [
    'default' => \SwFwLess\components\functions\env('REDIS_DEFAULT', 'default'),
    'connections' => [
        \SwFwLess\components\functions\env('REDIS_DEFAULT', 'default') => [
            'host' => \SwFwLess\components\functions\env('REDIS_HOST', '127.0.0.1'),
            'port' => \SwFwLess\components\functions\envInt('REDIS_PORT', 6379),
            'timeout' => \SwFwLess\components\functions\envDouble('REDIS_TIMEOUT', 1),
            'pool_size' => \SwFwLess\components\functions\envInt('REDIS_POOL_SIZE', 5),
            'passwd' => \SwFwLess\components\functions\env('REDIS_PASSWD', null),
            'db' => \SwFwLess\components\functions\envInt('REDIS_DB', 0),
            'prefix' => \SwFwLess\components\functions\env('REDIS_PREFIX', 'sw-fw-less:'),
        ],
        'zipkin' => [
            'host' => \SwFwLess\components\functions\env('REDIS_ZIPKIN_HOST', '127.0.0.1'),
            'port' => \SwFwLess\components\functions\envInt('REDIS_ZIPKIN_PORT', 6379),
            'timeout' => \SwFwLess\components\functions\envDouble('REDIS_ZIPKIN_TIMEOUT', 1),
            'pool_size' => \SwFwLess\components\functions\envInt('REDIS_ZIPKIN_POOL_SIZE', 5),
            'passwd' => \SwFwLess\components\functions\env('REDIS_ZIPKIN_PASSWD', null),
            'db' => \SwFwLess\components\functions\envInt('REDIS_ZIPKIN_DB', 1),
            'prefix' => \SwFwLess\components\functions\env('REDIS_ZIPKIN_PREFIX', 'sw-fw-less:zipkin:'),
        ],
        'red_lock' => [
            'host' => \SwFwLess\components\functions\env('REDIS_RED_LOCK_HOST', '127.0.0.1'),
            'port' => \SwFwLess\components\functions\envInt('REDIS_RED_LOCK_PORT', 6379),
            'timeout' => \SwFwLess\components\functions\envDouble('REDIS_RED_LOCK_TIMEOUT', 1),
            'pool_size' => \SwFwLess\components\functions\envInt('REDIS_RED_LOCK_POOL_SIZE', 5),
            'passwd' => \SwFwLess\components\functions\env('REDIS_RED_LOCK_PASSWD', null),
            'db' => \SwFwLess\components\functions\envInt('REDIS_RED_LOCK_DB', 2),
            'prefix' => \SwFwLess\components\functions\env('REDIS_RED_LOCK_PREFIX', 'sw-fw-less:lock:'),
        ],
        'rate_limit' => [
            'host' => \SwFwLess\components\functions\env('REDIS_RATE_LIMIT_HOST', '127.0.0.1'),
            'port' => \SwFwLess\components\functions\envInt('REDIS_RATE_LIMIT_PORT', 6379),
            'timeout' => \SwFwLess\components\functions\envDouble('REDIS_RATE_LIMIT_TIMEOUT', 1),
            'pool_size' => \SwFwLess\components\functions\envInt('REDIS_RATE_LIMIT_POOL_SIZE', 5),
            'passwd' => \SwFwLess\components\functions\env('REDIS_RATE_LIMIT_PASSWD', null),
            'db' => \SwFwLess\components\functions\envInt('REDIS_RATE_LIMIT_DB', 3),
            'prefix' => \SwFwLess\components\functions\env('REDIS_RATE_LIMIT_PREFIX', 'sw-fw-less:ratelimit:'),
        ],
        'cache' => [
            'host' => \SwFwLess\components\functions\env('REDIS_CACHE_HOST', '127.0.0.1'),
            'port' => \SwFwLess\components\functions\envInt('REDIS_CACHE_PORT', 6379),
            'timeout' => \SwFwLess\components\functions\envDouble('REDIS_CACHE_TIMEOUT', 1),
            'pool_size' => \SwFwLess\components\functions\envInt('REDIS_CACHE_POOL_SIZE', 5),
            'passwd' => \SwFwLess\components\functions\env('REDIS_CACHE_PASSWD', null),
            'db' => \SwFwLess\components\functions\envInt('REDIS_CACHE_DB', 4),
            'prefix' => \SwFwLess\components\functions\env('REDIS_CACHE_PREFIX', 'sw-fw-less:cache:'),
        ],
    ],
    'switch' => \SwFwLess\components\functions\envInt('REDIS_SWITCH', 0),
    'pool_change_event' => \SwFwLess\components\functions\envInt('REDIS_POOL_CHANGE_EVENT', 0),
    'report_pool_change' => \SwFwLess\components\functions\envInt('REDIS_REPORT_POOL_CHANGE', 0),
];
